name: Build and Deploy
on: [push]
  #push:
    #paths: ["src/stories/**", "src/components/**"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install, Build and Deploy 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
          npm run deploy-storybook
      